apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webhooks
  namespace: argo-events
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`webhooks.knodes.app`)
      kind: Rule
      services:
        - name: github-webhooks-eventsource-svc
          port: 12000
  tls:
    certResolver: letsencrypt
