---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-htpasswd
  namespace: registry
spec:
  encryptedData:
    htpasswd: AgCgwRTMNWNN/NEybu5EOwj50o9/WRThui/50H+JWFO/cj0E/q1elnHFS2UcTCuue5KvJjimLoRj4b0rKD9zTt4H05IxK4OxyTLcHZTmaU2CxmlfQzVRO+Z5sWMBEOusQR4+ckyqthHuP90ez7wlCt3yytt2JFzYGh0w4BuPoO/k+11XwcNtqj86J2l/NIYwirkArqRJBTgTmPpn35+ycyepEFkjelbHooOyU9DRB+W06n5ovLlpTFVNt/adqm11iSol6gU9uxl5uCFVisxtUnpAyjgMhg+iMjOpGptCzGEoag9cBYkJDL4hWyHfLVaz1z7sSsVe1HcbcuEkDjX1OGR1joq4+5mWLcnpNu901/qEzal3jyLMgc4S4lj1SEYJUuG1yr79LxOaJ4Y9VqdUg2wMjSP71QxXjAcGJpnwauP1kVxyA0uczie6b0DY0/un9PASMMYQ4GHtGSCj5mq1JBzvohu/AyhvdTJ3A1jhq/8bXzZJJebUIShSUnccfrOJ893urhx8uNflMoD9HCK5qjdUwZ3MN1P9RqtDiy/ekAH3/koyCUiiVNDaj6nQ+lKO9J43PyH70QcFsoJgyM6rG15KWAkZKJfc0bLr34xu1LLlpo9XG/omvsvY11PmMRvkfY4oI0ZjryL6pO7zLT+VJx+1UjM4SfYePspY39NeVPJDmOZAw4x1DPaUm3YqCpxqj5kyTGUVLK/Elq+ec9xz4z+PabJXys1H14bUCHEBLuhKAEzEs+QCdBKRtc9LTm/l5jayAiPr/qM5JwiIS8uY2GP01sjC
  template:
    metadata:
      name: registry-htpasswd
      namespace: registry
