---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull-secret
  namespace: knodes-backoffice
spec:
  encryptedData:
    .dockerconfigjson: AgAndsUomDdjWJdM+4bDmuQPne4dN9o/vHnPV+7XmBc5e/mPLXy9G+hk5pkKzcVwivbw6BMA+A7RLHnr/Kx6R5n3ZLurSCjg8Mw4LTOy4njo/Oi5opn+TWfDqx+9RD5wvR8oL/O7ccUvh1FBFYyMMkBLJjYCd7jN2FE8ZTnhhsKKE2SC+U0fISBvRsjzB3/ufCsrX5Hzg+BmYX1qheOHRJcGrG8HVgcRpoJPQreBpOKNAvSahQ6s+6Iy1yAck9HzDTSNydA31qGHfgUTdlb1ZM4cfqzJB1CXL9N5pa+DsrcyEus63eCnL/6Vvgs6KZcvgp18aG72VCKfzn7dqQTDFGjCQHlY1CkoCoaImkb2R2o475P+SD4eZey8KMpK9Y0XBsOqMolEkPl4COvj/qM/3A75gMp4cjMBRVoIDeOq5XohZ5jxak6J9Fm+FEbPJ14cjNv4Dee3Okn9Is/C+fB4XarKgxI0P5YwIDydp7vOx7Jracsvy9Noi4GnVXEJAoECaB4Z8CwGgPx1nDJVcQ508UwJEcM7K86VQZA5/U4WkM3I1rybzisRe1Xycl1025LxdQ/TDzNNtgjZyuplPPgbJsjfVa0upeIUp0Lp8m3Fh8A73dKW2vOcuTZUCc4jAJ6dxufmfAC31w/JFfGqBmG6X2ao+q5LcRwJjKtxWIOZ6VjErYRmOUH0n9LGtm2WjwQ98NF2wdaWI6s6Ko2jclQ7x16Q7l9tp33TpZ/cNHD0dqc5d3mWmrG4eTCvwSiESs2QHwHOkE9nsolyRM8kCLuEUOKmd0npUEe1KLFiPF/7pAFKrz7DDYEjdQvhaKW9RV4pg5Yb7XSXnqoZmPBGq/jhqvog9u0+yKErPri/MewHGV1XJd5Ds/sI3LDLwbqeN7Cg3wZB5680cS2zbxa5zWbU4py/q970FQDDK2MlI+ZfMNMCkuC1/P/11dg=
  template:
    metadata:
      name: registry-pull-secret
      namespace: knodes-backoffice
    type: kubernetes.io/dockerconfigjson
