apiVersion: apps/v1
kind: Deployment
metadata:
  name: knodes-backend
  namespace: knodes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knodes-backend
  template:
    metadata:
      labels:
        app: knodes-backend
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: backend
          image: registry.knodes.app/knodes-backend:b45970f340c6395afc25d2d7e57b07f80b72d963
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
