---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull-secret
  namespace: knodes-backend
spec:
  encryptedData:
    .dockerconfigjson: AgBXvsg+qOWkAT+0ZAOBuYhSGI98j1V32Ci5OPzsO+3wPa6RQKUTR+9NdTn1Rn4EoQ8VfEyk5sFKwwPzH5gqgC9ruUY5DKtpdsLS66Gl8i+1HMK93rQGSuz1//4nfQvOFKD1EYJKJ+poJUJP58xsJCAmtABrdconSKk0Ugecy3Bj4Cgn5tviNiAwtTqDa+2HX+iDNlPf0DyW62YRPSuAP22EuHS7B3ozK35MtD+93oFgeFwnbX+VVaUTqUtPeLoOmePpyMD3TbE6hhUxkd5iJoHCE+LWmJsCBzTMVwZcgKmIaZrSTFSZWwS6LtHO2vd4l8mbDzGB/EtZ397vnaAFa1KjL7j8/jyAfrd7ESuyPOK6h+RQatpyugdjZQI5MaCMSMopO0GVZWanJvx/2E01f4kERNPVP+oaazQgHisBR4dvN1lUZsWNay3qaAeqBeHw6N9Zekh/rIvxxIQ/Zl8K518UM/10DId3S4fSdgKQuAQZJCvIcczZKHc/nLf036KvfudkcuhS3/pxBbmHNM1c+SR2RFxAuhoChfdrdx/fwNZvONpZTjxFNyc4vC4RW8DDwB7YKy0NSuBJJJZa5UuBKxKlinyt3LhIXE38s81XqAh4LVYEJIouWkvQJqBfoIsKPHBwhcC84v7OuW+28+kRvcoQl/dxyBljWLp1AaW4xwtwDql2XCsdvFPo7KJwajZIz1IbRNwjV1DySBIVnJNkB9oLgVMyzQCqYcCMsPLgRPOc9WZKcwTdOLH04iPJH9cZoC1lrEzOdi9k3wSoEl7Tcf6CQDza8uCq2+BCq3IiZDkoPcRtExZeRpzTXADVWtbnQV4ywLB4HY1SMGm39LisNjNG8enhLlYS/uv6fKqph/1X1a7YjZ53QdYUCDJDvzqJJg6NUTxx/BSV52bvnPzJXBMj2SnAxRLqmX7Jm0kRcKuVjV3w4X8YRVg=
  template:
    metadata:
      name: registry-pull-secret
      namespace: knodes-backend
    type: kubernetes.io/dockerconfigjson
