---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-pull-secret
  namespace: knodes-app
spec:
  encryptedData:
    .dockerconfigjson: AgA1epxBhqerg/d7JeohCuDBho1IgI0FNL/AawUhvVSjlyO05ZMxv0lwlU615w4AeOhgMwMMGfF2GHtESRRc1lbrhNw3EKYnJdXe7Esexzjlf/CBuGWDzqJfEPv9/YyEj6LLyxrGbm7cZQ+trikI1pj3YnzRIZbTSZLTx6h7kDNVMToo4DVE0JkHwB77w6nYpI9OomJvD6fa/e111jSyJKIfqtPW5a48seeHDT+pGpVDxQt69LSV0pchF9Rm6Snkw8ZyfvLtfnLLKEBfgnnk0uu5BU/Y/uTRLF+Q0WfNdxHoZNGzn/DJe/aMzmf0JDbTZyjZ2qzV9B3wHbBS7VX7XNdey+FJlJ24XwXwwV5awClFGNR49DoYHIBdxafBfdF3biulwn/ly6f0vy2wkcTy3xHQ4aJtqKSfrlp1WjFzf+1xmu3h67U81VCGuKj5k8MzozC4aLTKfzQ9zGu8mQoPhtV3iID8nFQSTSazR8CUR3tmpgA/n4eAxxnGPBIf+tdwUlPG4Qx8Sczb1sEGhg+VGAMwX51ywD6MYsBbSoK+fe06pwZfKMmSrFT1NKAXOQPxqhPHO6ObatQQyEAChBdf2G2SPVIZkU1pjmy1SMwR7VvbyQif/NLqMW1355Kk4tgtqPSXinZGJP0+mg1HD33VAEtzoEkXADfTnckbCXeyY4MHy5FXEoz1qf2oC8u5NxhsKxzSXITYUygAxP2d5EvKYQkRNrk7JHYog1tmcJtTb6fywDQDTAiJkP3WyxHHvKgjllHnOFDKQn9+kt2y5h6zm1u2zLw1Z0s5KwHZKHBlTs4qmAP3bTCIwrDu/yxXiazW7IY+sKjI2XYtXqPKGgiTqAoQPBGNVFzGCtPM7pk1+Mj+tTGkAw5hXlYQvU9PrXQuV9oeH+b68p62wt3Lk5ZBVYhVkQ61hwT7g7dZupj8+PnMlIwJMq5BKkE=
  template:
    metadata:
      name: registry-pull-secret
      namespace: knodes-app
    type: kubernetes.io/dockerconfigjson
