apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/syzore/WorldKnowledgeGraph-Cluster-Config.git
    targetRevision: main
    path: charts/game-2048
  destination:
    server: https://kubernetes.default.svc
    namespace: games
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
