apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/syzore/WorldKnowledgeGraph-Cluster-Config.git
    targetRevision: main
    path: infra/neo4j
  destination:
    server: https://kubernetes.default.svc
    namespace: knodes-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
