apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: knodes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
        - name: neo4j
          image: neo4j:latest
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-credentials
                  key: auth
            - name: NEO4J_server_memory_heap_initial__size
              value: "1024m"
            - name: NEO4J_server_memory_heap_max__size
              value: "1500m"
            - name: NEO4J_server_memory_pagecache__size
              value: "1g"
          resources:
            requests:
              memory: 2Gi
            limits:
              memory: 3Gi
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neo4j-data
