---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-credentials
  namespace: knodes-backend
spec:
  encryptedData:
    auth: AgCE38j7nmWB+MpUTEk8VVA4BJIEJgTiuB7SEdpL+slKf7k6kiCabha++0902eT+DbU3mLNiYpJ36uQ/fPEeOc+5mhXnnHEIzOD8M1shjE3dPGT8KpGswGz2M0daNzYf7LYVTn7nIE4pt5ZIAUFUsSGpHUks8J6Bq+wIBx7QmAbb3bsHhQwX/pjYqGnP23ePrg6RMq/SUI6KUcRtXxA7QuJgreE68d95vQ395k2Wdhzi8eDF9XOwLUYs3kgTyl8GVoCXpMpfJhyN+B/ACfnh9vTDzACC8Y1SRmRx60BtA7xA2UpZ0TuX79Lux3ru4K8nKL3u83ghFwWZU7X5r0/D9gFdHHUaTyVct7Xgo8gKgjQqhk5X1egRrxbxIWNfOkVyGKqg0T2IHrdSjxNrZMxBTUZ7BtU0lZXVIDrWyrZh3NDj1xsiVSohCSqCtFYQoLHliby6HxxPw28ySa1hM4Mulp1NcROBCXr10kn1FEtohhcumX874U3P3gj8DrtEL+bdtRPdIIYZq3PuelHljtos6wpepqvfGtW7hpQulD27/ahjncILZpOdNKsohcl68AkglPqUD2TMalD7Xl7wkiZQDCdJeW81TF4n0agv+dBmTt5Cp8+l4FDgJ4qtTKD3ovJDxXA+1r73rDYCy4EGm+0gBwg62JfHfZ+OCuDLSNKvSTz4TkXBR0ARgEZj9+mJ30ztL+SiGOMpV/XSHKhzPfdxG3xk6E9goMjXl5D/Mcwo6jSaF6T4239Ja72AWaxFX/wL
  template:
    metadata:
      name: neo4j-credentials
      namespace: knodes-backend
