---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-credentials
  namespace: knodes-backend
spec:
  encryptedData:
    password: AgBy7XqKlV6Eq1hYi3P2TD6f9Olo/ZI+ognzf8GrIIGHa9ar/Dtw9xdxpu1krnJsJBinIpjuyVrkVJSV2J9gqqcNmzdzrLiskToOs966L19JEsLhMQz90SadpG7qRd3G+3aUMCh+vUNAgBGqbXRTDOknjGD0DWxT60SSVzPukgWxj5cXlBytNt4kzoqkE3kbJoNmP0axBgRvGYE9LqI7ujbJjEUN3Q+OaVgV9TPHoWCLpmju0enFadBnMekS094P3FfIfLp4/TPrrwnZlxfRmEGBTKH6UXUAIR2hJXQ3ifYGP/e1u56zSyOs1N4HIWyviE1X7SjxQbBsCROz1kq82+zhy2hLHFvY3pbLZXhjMds0dxV/uInG7iIPiJaiB2ZbzrhPFTgVUdSaEIg58EJNuc9n2y2/RFR4QedNVwx4D2r0yJioeImLJwD6cMo+dF49A3q2TrtsQ5VNnpXMtPcpnOlgE1FkWOXJL/a7aatR1nlgPmUZZHej06LA7aqQ7k2LOJZxyrzfeb5mF8677R0W5hdWzaED7LrzGilO0mn7Sl0hQISZdpl3uHGO6SQNLrLcevBRPFhtVEBeyivYMnsacIQhgdc67CyRAkp3eh3ppRYlbZhlsxJzaC4tHMuiz4mLybmXhquMCJYUrq6FzccXauIRPd/ok8snoF9Vur/z1vecNKlUkOZUCjWBavbCxO6vLBd17JCR/hDFzuKLzo8v4BluHs6nnY4Xd97bY/H7LiCoQwCRRwVudqEd
  template:
    metadata:
      name: neo4j-credentials
      namespace: knodes-backend
