---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-push-credentials
  namespace: argo
spec:
  encryptedData:
    password: AgA1qNb6pzYmoO5wOIaZtjuc1sbY/YssV0lCy8ar1sIjyl4/l9YlmnItgQc60fstwvSJHRmae1UFU4urnOZLkluysm58pI8kg3bJ/kzDKp8wg8U4vP2+Cg1oo1VK3eq2U7bmSAPisjGE8XfQiAzzFwUWbFxUn5s/Yn9ktZUsZF2RHsgIe3dY5Yqupl3MNQrRk996pikzEYD1IUyZU4CWBXaBn7ycRd3Jx8BLZ9vjXKOyihYMg9eHKYuYpeDkGMU8FML/ce7hup+l1dUtIN4WhsftPFwF1mmsoXhPdJ+eezgJTEw56DoZQJfFe6mLyWcNQTmvIpAXn3Dk2nlv8dqkmit5pHfdgYo1LCaBO1iA3SCsXSFAyrBiYBNRLR6U8We5ONWUhtyhqG4aFgUYX0KB4zS2buR88J10OJe+vIsxG5FDnSD2YOOO/puVBGUpANnRBxHa1B0dSmRBE7v7RAa/bFIdcnf0LjXkYuDS63Q6WDlN7zhwA4Z44Vpyle/12hLF+hDdRIahJnxYmEc0eb0HsxrX9T0zQjCc3z5SI2wXGVF7A1Nyfy7QvVm1UjuS02L9n74/n2R5yAnHfLSh3tZQ4rcJKlNagjNud20KCJ/7IusswdRs4fUJenDcc/1jmqsC0547BFPNCNzfD/gfRf0szvCIPVFMyxcU117Fk4vVrTJnmZnKYyVpvgd+Z7BHVTs9SFTPzIldvx+X5yc4Yee/jx07K2aknkmoopfhVGHvb6xExf0gSwJIElo2
    username: AgDGZHdE/fO6rWUB3Zl5wUvuNrAPb+ljk6LmIVqlbBr1lJQubj9Pa9hOEYzKy0y6Nro/Rdo8QwHDzX7pdRSdvOu/u+YcifGvhGsRF0IY9wh1qU8LXqCUZ0Eu8UGwbh1zPpnjQHitGQDu+3NaltH8EpOlwj6U6TAq3+Tty7abWv8UC77bdWyd4eqe7UldRFIdqpIGjHeXUDfy0F3Hsd60dMwzf2c3j+GFBjWKI3EUIQX/iOtcDysvbtip2i1qF2Kp9ZMTBH838bNE9yX2sbqCCvytnzFIp1+fOp/cERNUCirFsfKcJBjlPeu/3WXpZLPpAz5q1Z6dGD9/lY2GUrsPveTo0Y3nzo/3RFsCjXWzmjxTrULsOm1pdZ1l3IIeOvesbh2darRtWrbQEeRQpzFLj4+PE5bVyuj0xjpHmDPXvfrZbDggUiyN4m6ENJ7VJCTeB/2jSl1BOIbfvDOXz4fU/Ge06/AP2LGBSKbfe+6+NFoqaGkXvBvho1JqMGqrhzbODTH5MIx8xJO6/rrb3EnkVFJaq/WqqhtyncC2tKqkWlkQyyvGZP+HG90qVoZtyJDKrZkQAGoNRIQCOpDvf0JFyZ7SNcmkrVk4rrMkGLfvt71YQ3mMR9zUuXP+rBQ9dcg1ulvSHmTNHxE20OqCNuG1+Yz8zMRx8g8tRbqKdRqlA3d587ogltTyOeqo9dPfYecQq5xPwt1ruHc=
  template:
    metadata:
      name: registry-push-credentials
      namespace: argo
